// The multilingual build (playbook §2-6, §10-11). English in src/ is the single source; website/i18n/<lang>.json are
// the translations. build() renders every version in memory and refuses (writes nothing) on a stale catalogue, a
// missing id, changed markup or placeholders, a dropped protected name, a snippet over its limit, a page over the
// size budget, or English left on a translated page.
import { createHash } from 'node:crypto';
import { readFileSync, existsSync, readdirSync } from 'node:fs';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { LANGS, ORIGIN, PROTECT, withLang, t, validate, staleIds, textRuns, decode } from './i18n.mjs';
import { renderPage } from './page.mjs';
import { render404, strings404 } from './notfound.mjs';

export const WEB = new URL('../', import.meta.url);             // website/
export const SRC = new URL('./', import.meta.url);              // website/src/
const dirURL = p => pathToFileURL(resolve(p) + '/');
// I18N_DIR (translations, catalogue, locks) and OUT_DIR (the site root) override website/i18n and website/
export const defaults = () => ({
  i18nDir: process.env.I18N_DIR ? dirURL(process.env.I18N_DIR) : new URL('i18n/', WEB),
  outDir: process.env.OUT_DIR ? dirURL(process.env.OUT_DIR) : WEB,
});
export const MAX_BYTES = 153600;
const LASTMOD = '2026-09-25';
const sha = b => createHash('sha256').update(b).digest('hex');
const read = u => (existsSync(u) ? readFileSync(u) : null);

// The suggestion bar's strings (src/langbar.js); each version carries them for every language, since the bar is
// shown in the language it offers.
export const barStrings = () => ({
  msg: t('This page is also available in English.', 'suggestion bar: one line shown to visitors whose browser prefers your language, on a page in another language. Name your language as a reader would (“…in Spanish” → “…en español”)', { kind: 'js' }),
  go: t('Read it in English', 'suggestion bar: the link to this version (short; name your language)', { kind: 'js' }),
  close: t('Dismiss', 'suggestion bar: accessible name of the × button that closes it', { kind: 'js' }),
});

const ABOUT = [
  'The GenSwarms landing page catalogue: every string the page shows or reads out, in English. Generated by `node website/build.mjs --extract`; do not edit.',
  'To translate: write website/i18n/<file>.json (file: es, ko, zh, ru, tr) as a JSON object { "<id>": "<translation>", … } with every id below, plus "_same_as_english": [ids] for strings whose right translation is the English itself (they are checked, so list them deliberately). Keep your term decisions in website/i18n/<file>.ledger.md.',
  'kind: meta = search and share snippets (plain text); html = the inner HTML of one element (keep every tag exactly, same attributes; &nbsp; is a non-breaking space you may keep, move or drop); attr = an accessible name or tooltip (plain text, no tags); svg = a label drawn inside a figure (plain text, short); js = the suggestion bar, shown to readers whose browser prefers your language; 404 = the not-found page.',
  'placeholders: {n}, {title}, {cap} are filled in by the page. Keep each exactly once, in the place your grammar needs.',
  'max (svg labels): about how many Latin or Cyrillic characters fit on one line; count each Chinese or Korean character as two. lines: how many lines the label may wrap to (1 = it must fit on one line; a longer one is set smaller). Stay within it: the build fits what it can, and the layout audit fails on labels that overlap.',
  'limit: a hard limit in characters; chars for most languages, cjk for Chinese and Korean. The build refuses longer text.',
  'Protected names (_protect) must appear verbatim in your translation whenever the English has them. Names in the keep list (product, company and language names, file names, and the identifiers drawn in the figures such as telegram, triage, message_routed, swarm.state) are not in the catalogue: they stay as they are.',
  'Constraints (playbook §8): translate by meaning, not word by word; do not make text longer than the English (it has to fit the layout); do not strengthen claims; use the same term for the same concept everywhere.',
];

// the catalogue: render everything once in English with a recorder attached
export function catalogue() {
  const rec = new Map();
  withLang({ rec }, () => {
    renderPage({ langs: LANGS, bar: {} });
    strings404();
    barStrings();
  });
  return [...rec.values()];
}
export const catalogueFile = entries => JSON.stringify({ _about: ABOUT, _protect: PROTECT, _languages: Object.fromEntries(LANGS.slice(1).map(l => [l.file, `${l.name} (${l.code}): website/${l.dir}`])), entries }, null, 1) + '\n';

const ogKey = l => l.file || 'en';
export const ogFile = l => (l.file ? `og-${l.file}.png` : 'og-image.png');
// what a share image shows: the hero (headline, lead, buttons and its drawing), hashed. tools/og.cjs records the
// same hash for each image it renders, so a changed headline makes its image stale.
export const ogSource = html => sha(html.match(/<article class="step step-hero" id="s0"[\s\S]*?<\/article>/)[0]);

const segments = html => html.split(/<[^>]+>/).map(s => decode(s).replace(/\s+/g, ' ').trim()).filter(Boolean);

function sitemap(langs) {
  if (langs.length === 1) return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n  <url>\n    <loc>${ORIGIN}</loc>\n    <lastmod>${LASTMOD}</lastmod>\n    <changefreq>weekly</changefreq>\n    <priority>1.0</priority>\n  </url>\n</urlset>\n`;
  const alts = [...langs.map(l => `    <xhtml:link rel="alternate" hreflang="${l.code}" href="${ORIGIN}${l.dir}"/>\n`), `    <xhtml:link rel="alternate" hreflang="x-default" href="${ORIGIN}"/>\n`].join('');
  return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">\n` +
    langs.map(l => `  <url>\n    <loc>${ORIGIN}${l.dir}</loc>\n    <lastmod>${LASTMOD}</lastmod>\n    <changefreq>weekly</changefreq>\n    <priority>1.0</priority>\n${alts}  </url>\n`).join('') + '</urlset>\n';
}
// llms.txt stays English and hand-written; the build keeps one line listing the language versions
function llms(src, langs) {
  const base = src.replace(/^Language versions of this page: .*\n/m, '');
  if (langs.length === 1) return base;
  const line = `Language versions of this page: ${langs.map(l => `${l.name} ${ORIGIN}${l.dir}`).join(', ')}.\n`;
  return base.replace(/^(Current version: .*\n)/m, `$1${line}`);
}

// build({ i18nDir, outDir }) -> { outputs: { 'es/index.html': string | null (delete) , … }, lock, langs, errors, notes }
export function build({ i18nDir, outDir } = defaults()) {
  const errors = [], notes = [];
  const entries = catalogue();
  // 1. the catalogue must match the English source
  const cat = read(new URL('en.json', i18nDir));
  const have = cat ? JSON.parse(cat).entries : [];
  if (!cat || JSON.stringify(have) !== JSON.stringify(entries)) {
    const now = new Set(entries.map(e => e.id)), before = new Set(have.map(e => e.id));
    const added = [...now].filter(i => !before.has(i)), gone = [...before].filter(i => !now.has(i));
    return { errors: [`website/i18n/en.json is stale: the English source changed since the last extract${added.length ? ` (new or changed ids: ${added.join(' ')})` : ''}${gone.length ? ` (gone: ${gone.join(' ')})` : ''}. Run \`node website/build.mjs --extract\`, translate the ids it reports, then build.`] };
  }
  // 2. every translation file present is complete and well-formed
  const langs = [LANGS[0]], tables = {};
  for (const l of LANGS.slice(1)) {
    const raw = read(new URL(`${l.file}.json`, i18nDir));
    if (!raw) continue;
    let tx;
    try { tx = JSON.parse(raw); } catch (e) { errors.push(`${l.code}: ${l.file}.json is not valid JSON: ${e.message}`); continue; }
    errors.push(...validate(l.code, entries, tx).map(m => `${l.code}: ${m}`));
    const stale = staleIds(entries, tx);
    if (stale.length) notes.push(`${l.code}: ids no longer in the catalogue (safe to delete): ${stale.join(' ')}`);
    langs.push(l); tables[l.code] = tx;
  }
  if (errors.length) return { errors };

  // 3. render every version
  const tableOf = l => (l.code === 'en' ? null : tables[l.code]);
  const bar = Object.fromEntries(langs.map(l => [l.code, { ...withLang({ lang: l.code, table: tableOf(l) }, barStrings), href: '/' + l.dir }]));
  const outputs = {}, pages = {};
  for (const l of langs) {
    const html = withLang({ lang: l.code, table: tableOf(l) }, () => renderPage({ lang: l.code, langs, bar, ogImage: ogFile(l) }));
    pages[l.code] = html;
    outputs[`${l.dir}index.html`] = html;
    if (Buffer.byteLength(html) >= MAX_BYTES) errors.push(`${l.code}: ${l.dir}index.html is ${Buffer.byteLength(html)} bytes, over the ${MAX_BYTES}-byte budget`);
  }
  // 4. no English left behind: every text run a translated page shares with the English page must be a name, an
  // identifier, or an id the language file lists under _same_as_english
  const enRuns = textRuns(pages.en);
  for (const l of langs.slice(1)) {
    const same = new Set(tables[l.code]._same_as_english || []);
    const allowed = new Set(entries.filter(e => same.has(e.id)).flatMap(e => segments(e.en)));
    const left = [...textRuns(pages[l.code])].filter(r => enRuns.has(r) && !allowed.has(r));
    if (left.length) errors.push(`${l.code}: the built page still shows English: ${left.map(r => JSON.stringify(r.slice(0, 60))).join(', ')}`);
  }
  if (errors.length) return { errors };
  // versions no longer translated are removed
  for (const l of LANGS.slice(1)) if (!langs.includes(l) && existsSync(new URL(`${l.dir}index.html`, outDir))) outputs[`${l.dir}index.html`] = null;

  const byLang = Object.fromEntries(langs.slice(1).map(l => [l.dir.replace('/', ''), { lang: l.code, home: '/' + l.dir, ...withLang({ lang: l.code, table: tables[l.code] }, strings404) }]));
  outputs['404.html'] = render404(byLang);
  outputs['sitemap.xml'] = sitemap(langs);
  outputs['llms.txt'] = llms(readFileSync(new URL('llms.txt', WEB), 'utf8'), langs);

  const files = { 'en.json': sha(cat), ...Object.fromEntries(langs.slice(1).map(l => [`${l.file}.json`, sha(read(new URL(`${l.file}.json`, i18nDir)))])) };
  const lock = {
    _about: 'Written by `node website/build.mjs` after a successful build; `--check` (CI, deploy) refuses when the English source, a translation or a built file no longer matches it.',
    source: sha(readdirSync(SRC).sort().map(f => f + '\0' + readFileSync(new URL(f, SRC), 'utf8')).join('\0')),
    i18n: files,
    outputs: Object.fromEntries(Object.entries(outputs).filter(([, v]) => v !== null).map(([k, v]) => [k, sha(v)])),
    og: Object.fromEntries(langs.map(l => [ogKey(l), { image: ogFile(l), source: ogSource(pages[l.code]) }])),
  };
  return { outputs, lock, langs, errors, notes, pages };
}

// check: the committed outputs and the lock are what the current sources build, and every share image was
// rendered from its page's current hero and not edited since (i18n/og.lock.json, written by tools/og.cjs)
export function check({ i18nDir, outDir } = defaults()) {
  const r = build({ i18nDir, outDir });
  if (r.errors.length) return r.errors;
  const bad = [];
  for (const [f, v] of Object.entries(r.outputs)) {
    const cur = read(new URL(f, outDir));
    if (v === null) { if (cur) bad.push(`website/${f} is a version that is no longer translated: run \`node website/build.mjs\``); continue; }
    if (!cur || cur.toString('utf8') !== v) bad.push(`website/${f} is stale: run \`node website/build.mjs\``);
  }
  const lock = read(new URL('build.lock.json', i18nDir));
  if (!lock) bad.push('website/i18n/build.lock.json is missing: run `node website/build.mjs`');
  else if (JSON.stringify(JSON.parse(lock)) !== JSON.stringify(r.lock)) {
    const L = JSON.parse(lock), diff = [];
    if (L.source !== r.lock.source) diff.push('the English source (website/src)');
    for (const k of new Set([...Object.keys(L.i18n || {}), ...Object.keys(r.lock.i18n)])) if ((L.i18n || {})[k] !== r.lock.i18n[k]) diff.push(`i18n/${k}`);
    for (const k of new Set([...Object.keys(L.outputs || {}), ...Object.keys(r.lock.outputs)])) if ((L.outputs || {})[k] !== r.lock.outputs[k]) diff.push(k);
    bad.push(`website/i18n/build.lock.json does not match ${diff.join(', ') || 'the build'}: run \`node website/build.mjs\``);
  }
  const og = read(new URL('og.lock.json', i18nDir));
  const ogl = og ? JSON.parse(og) : {};
  for (const [k, { image, source }] of Object.entries(r.lock.og)) {
    const png = read(new URL(image, outDir)), got = ogl[k] || {};
    if (got.source !== source) bad.push(`website/${image} shows an old hero (or was never rendered): run \`node website/tools/og.cjs\` with the site served`);
    else if (!png || sha(png) !== got.png) bad.push(`website/${image} changed since tools/og.cjs rendered it`);
  }
  return bad;
}

// verify <base>: every version served right: 200s, /es -> /es/, lang, title, canonical, reciprocal hreflang
export async function verify(base, langs) {
  base = base.replace(/\/?$/, '/');
  const bad = [], log = [];
  const get = async u => { try { const r = await fetch(u, { redirect: 'follow' }); return { st: r.status, url: r.url, body: await r.text() }; } catch (e) { return { st: 0, url: u, body: String(e) }; } };
  const want = new Set([...langs.map(l => `${l.code} ${ORIGIN}${l.dir}`), `x-default ${ORIGIN}`]);
  for (const l of langs) {
    const { st, body } = await get(base + l.dir);
    const lang = (body.match(/<html[^>]*\blang="([^"]+)"/) || [])[1];
    const canon = (body.match(/<link rel="canonical" href="([^"]+)"/) || [])[1];
    const title = (body.match(/<title>([\s\S]*?)<\/title>/) || [])[1];
    const alts = new Set([...body.matchAll(/<link rel="alternate" hreflang="([^"]+)" href="([^"]+)"/g)].map(m => `${m[1]} ${m[2]}`));
    log.push(`${base + l.dir}: ${st} lang=${lang} canonical=${canon} title=${JSON.stringify((title || '').slice(0, 60))}`);
    const at = l.dir || '/';
    if (st !== 200) bad.push(`${at} returned ${st}`);
    if (lang !== l.code) bad.push(`${at} lang is ${lang}, not ${l.code}`);
    if (canon !== ORIGIN + l.dir) bad.push(`${at} canonical is ${canon}`);
    if (!title || !title.trim()) bad.push(`${at} has no title`);
    if (langs.length > 1 && [...want].some(w => !alts.has(w))) bad.push(`${at} hreflang set differs: ${[...want].filter(w => !alts.has(w)).join(', ')} missing`);
    if (l.dir) {
      const r2 = await get(base + l.dir.replace(/\/$/, ''));
      if (r2.st !== 200 || !r2.url.endsWith('/' + l.dir)) bad.push(`/${l.dir.replace(/\/$/, '')} does not redirect to /${l.dir} (${r2.st}, ${r2.url})`);
    }
  }
  for (const f of ['sitemap.xml', 'robots.txt', 'llms.txt', '404.html', ...langs.map(ogFile)]) {
    const { st } = await get(base + f);
    if (st !== 200) bad.push(`/${f} returned ${st}`);
  }
  return { bad, log };
}
