defmodule Genswarms.Config.ExsWriter do
  @moduledoc """
  Emits an Elixir `.exs` swarm configuration from a `SwarmConfig` struct.

  Used by `swarm snapshot` to consolidate the in-memory state (seed ⊕ overlay)
  into a fresh declarative config. The output is formatted with
  `Code.format_string!/1`.

  Limitations:
    * Anonymous functions in the original config are not representable.
    * Dynamic expressions (e.g. `for i <- 1..N do ... end`) are expanded
      into their static result. Comments and original formatting are not
      preserved.
  """

  alias Genswarms.Config.SwarmConfig

  # Map keys whose name looks secret-bearing; their values are redacted before a
  # config/backend map is serialized, so a snapshot never persists secrets
  # (api_key, env passwords/tokens, …) in cleartext (CWE-312). Matches e.g.
  # api_key, SUBZEROCLAW_API_KEY, DB_PASSWORD, *_TOKEN, *secret*.
  @sensitive_key_regex ~r/(?:key|secret|token|password|passwd|credential)/i
  @redaction_placeholder "[REDACTED]"

  # Keys that match the regex but name a non-secret (a path/reference, not the
  # secret value itself) — must NOT be redacted or snapshot round-trip breaks
  # (e.g. an SSH agent's key_path is a filename, not a private key).
  @redaction_exceptions ~w(key_path)

  @spec to_exs_source(SwarmConfig.t()) :: String.t()
  def to_exs_source(%SwarmConfig{} = config) do
    header =
      "# Generated by Genswarms.Config.ExsWriter at #{DateTime.utc_now() |> DateTime.to_iso8601()}\n"

    snapshot = %{
      name: config.name,
      agents:
        Enum.map(config.agents, fn spec ->
          snapshot_spec(spec, [:name, :backend, :skills, :model, :endpoint, :presets, :config])
        end),
      objects:
        Enum.map(config.objects || [], fn spec ->
          snapshot_spec(spec, [:name, :handler, :backend, :config])
        end),
      topology: config.topology
    }

    formatted =
      snapshot
      |> inspect(
        limit: :infinity,
        printable_limit: :infinity,
        charlists: :as_lists,
        structs: false
      )
      |> Code.format_string!()
      |> IO.iodata_to_binary()

    header <> formatted <> "\n"
  end

  defp snapshot_spec(spec, keys) do
    spec
    |> Map.take(keys)
    |> Map.put(:name, Map.get(spec, :name))
    |> Enum.reject(fn
      {key, nil} when key in [:backend, :handler, :model, :endpoint] -> true
      {key, []} when key in [:skills, :presets] -> true
      {:config, value} when value == %{} -> true
      _ -> false
    end)
    |> Map.new(fn
      {key, value} when key in [:backend, :config] -> {key, redact_secrets(value)}
      field -> field
    end)
  end

  # Recursively replace the value of any map key whose name looks sensitive with
  # a placeholder. Walks nested maps/lists/tuples so secrets inside backend opts
  # and extra_env are caught too. The snapshot deliberately does not round-trip
  # the real secret — the operator restores it via env (e.g. SUBZEROCLAW_API_KEY).
  defp redact_secrets(map) when is_map(map) do
    Map.new(map, fn {k, v} ->
      if sensitive_key?(k), do: {k, @redaction_placeholder}, else: {k, redact_secrets(v)}
    end)
  end

  defp redact_secrets(list) when is_list(list), do: Enum.map(list, &redact_secrets/1)

  defp redact_secrets(tuple) when is_tuple(tuple) do
    tuple |> Tuple.to_list() |> Enum.map(&redact_secrets/1) |> List.to_tuple()
  end

  defp redact_secrets(other), do: other

  defp sensitive_key?(key) do
    str = to_string(key)
    str not in @redaction_exceptions and String.match?(str, @sensitive_key_regex)
  end
end
